"""prompts — 提示词域：诊断/讨论/摘要/方案等 prompt 模板与组装工具。"""
from ai.agents.AiTaskPlatform.prompts.prompts import (
    DIAGNOSE_SYSTEM_PROMPT,
    DIAGNOSE_USER_TEMPLATE,
    DISCUSS_SYSTEM_PROMPT,
    DISCUSS_USER_TEMPLATE,
    SUMMARIZE_SYSTEM_PROMPT,
    SUMMARIZE_FULL_TEMPLATE,
    SUMMARIZE_INCREMENTAL_TEMPLATE,
    TASK_AGENT_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE,
)
from ai.agents.AiTaskPlatform.prompts.prompt_builder import build_user_prompt

__all__ = [
    "DIAGNOSE_SYSTEM_PROMPT", "DIAGNOSE_USER_TEMPLATE",
    "DISCUSS_SYSTEM_PROMPT", "DISCUSS_USER_TEMPLATE",
    "SUMMARIZE_SYSTEM_PROMPT", "SUMMARIZE_FULL_TEMPLATE",
    "SUMMARIZE_INCREMENTAL_TEMPLATE", "TASK_AGENT_SYSTEM_PROMPT",
    "USER_PROMPT_TEMPLATE", "build_user_prompt",
]
