"""sync_schema

Revision ID: 26021ebb27b1
Revises: c6281d3a8cf4
Create Date: 2026-07-29 09:31:14.090073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26021ebb27b1'
down_revision: Union[str, None] = 'c6281d3a8cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('enabled', sa.String(length=8), nullable=False))
    op.add_column('project', sa.Column('project_type', sa.String(length=20), nullable=True, comment='项目类型（企业微信项目类型字段原值）'))
    op.add_column('project', sa.Column('stage_notes', sa.Text(), nullable=True, comment='生命周期各阶段补充说明(JSON格式，键为阶段名)'))
    op.add_column('project', sa.Column('risk_carrying_type', sa.String(length=20), nullable=True, comment='风险承接类型'))
    op.add_column('project', sa.Column('special_attention', sa.Text(), nullable=True, comment='特别关注说明'))
    op.add_column('project', sa.Column('risk_task_description', sa.Text(), nullable=True, comment='风险和任务描述'))
    op.add_column('project', sa.Column('management_strategy', sa.Text(), nullable=True, comment='项目管理策略'))
    op.add_column('project', sa.Column('project_documents', sa.Text(), nullable=True, comment='项目文档(JSON格式，[{name,resource_id,url}])'))
    op.add_column('project', sa.Column('sales', sa.String(length=50), nullable=True, comment='销售'))
    op.add_column('project', sa.Column('pre_sales', sa.String(length=50), nullable=True, comment='售前'))
    op.add_column('project', sa.Column('project_manager', sa.String(length=50), nullable=True, comment='项目经理'))
    op.add_column('project', sa.Column('field_engineer', sa.String(length=50), nullable=True, comment='实施工程师'))
    op.add_column('project', sa.Column('internal_code', sa.String(length=50), nullable=True, comment='内部编号'))
    op.add_column('project', sa.Column('project_region', sa.String(length=30), nullable=True, comment='项目区域/地点'))
    op.add_column('project', sa.Column('total_vehicle_count', sa.Integer(), nullable=True, comment='总车数'))
    op.add_column('project', sa.Column('controller_vendor', sa.String(length=30), nullable=True, comment='控制器选择'))
    op.add_column('project', sa.Column('system_integration', sa.Text(), nullable=True, comment='系统/外设对接(JSON数组)'))
    op.add_column('project', sa.Column('server_deployment_status', sa.String(length=30), nullable=True, comment='服务器部署'))
    op.alter_column('project', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_comment='项目描述',
               existing_nullable=True)
    op.alter_column('project', 'risk_list',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.Text(),
               existing_comment='风险清单',
               existing_nullable=True)
    op.alter_column('project', 'recent_delivery_content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.Text(),
               existing_comment='近期交付内容',
               existing_nullable=True)
    op.alter_column('project', 'project_summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_comment='项目总结',
               existing_nullable=True)
    op.alter_column('project', 'field_links',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_comment='字段链接(JSON格式)',
               existing_nullable=True)
    op.add_column('project_license', sa.Column('machine_code', sa.String(length=200), nullable=True, comment='机器码/MAC地址'))
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('NEW', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('NEW', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CANCELED', 'CLOSED', name='taskstatus'),
               existing_comment='任务状态',
               existing_nullable=False)
    op.alter_column('tasks', 'canceled_at',
               existing_type=mysql.DATETIME(),
               comment='取消时间',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=128),
               comment='部门/团队',
               existing_comment='部门',
               existing_nullable=True)
    op.alter_column('users', 'responsibility_modules',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_comment='责任模块(JSON数组)',
               existing_nullable=True)
    op.alter_column('users', 'job_level',
               existing_type=mysql.INTEGER(),
               type_=mysql.TINYINT(),
               nullable=False,
               comment='职级，数值越高越不优先接单（1=一线, 2=管理/审核, 3=仅兜底...），默认1',
               existing_comment='职级',
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'duty_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='职责画像文本，供 AI 派单匹配参考',
               existing_comment='职责描述',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'duty_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='职责描述',
               existing_comment='职责画像文本，供 AI 派单匹配参考',
               existing_nullable=True)
    op.alter_column('users', 'job_level',
               existing_type=mysql.TINYINT(),
               type_=mysql.INTEGER(),
               nullable=True,
               comment='职级',
               existing_comment='职级，数值越高越不优先接单（1=一线, 2=管理/审核, 3=仅兜底...），默认1',
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'responsibility_modules',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='责任模块(JSON数组)',
               existing_comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='部门',
               existing_comment='部门/团队',
               existing_nullable=True)
    op.alter_column('tasks', 'canceled_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='取消时间',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CANCELED', 'CLOSED', name='taskstatus'),
               type_=mysql.ENUM('NEW', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', collation='utf8mb4_unicode_ci'),
               existing_comment='任务状态',
               existing_nullable=False)
    op.drop_column('project_license', 'machine_code')
    op.alter_column('project', 'field_links',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_comment='字段链接(JSON格式)',
               existing_nullable=True)
    op.alter_column('project', 'project_summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_comment='项目总结',
               existing_nullable=True)
    op.alter_column('project', 'recent_delivery_content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_comment='近期交付内容',
               existing_nullable=True)
    op.alter_column('project', 'risk_list',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_comment='风险清单',
               existing_nullable=True)
    op.alter_column('project', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_comment='项目描述',
               existing_nullable=True)
    op.drop_column('project', 'server_deployment_status')
    op.drop_column('project', 'system_integration')
    op.drop_column('project', 'controller_vendor')
    op.drop_column('project', 'total_vehicle_count')
    op.drop_column('project', 'project_region')
    op.drop_column('project', 'internal_code')
    op.drop_column('project', 'field_engineer')
    op.drop_column('project', 'project_manager')
    op.drop_column('project', 'pre_sales')
    op.drop_column('project', 'sales')
    op.drop_column('project', 'project_documents')
    op.drop_column('project', 'management_strategy')
    op.drop_column('project', 'risk_task_description')
    op.drop_column('project', 'special_attention')
    op.drop_column('project', 'risk_carrying_type')
    op.drop_column('project', 'stage_notes')
    op.drop_column('project', 'project_type')
    op.drop_column('permissions', 'enabled')
    # ### end Alembic commands ###
