"""数据指标插入

Revision ID: 2b7155c7fb55
Revises: 87e115802055
Create Date: 2026-08-17 13:14:56.114221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b7155c7fb55'
down_revision: Union[str, None] = '87e115802055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_tz_migration_sentinel')
    op.alter_column('collection_data', 'data',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('history_data', 'data',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('project', 'settlement_period',
               existing_type=mysql.VARCHAR(length=20),
               comment='业绩核算期（手工填写，常见YYYYMM如202608，兼容YYYY-MM）',
               existing_comment='业绩核算期，格式YYYY-MM',
               existing_nullable=True)
    op.alter_column('project_daily_report', 'report_content',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_comment='日报内容(JSON格式)',
               existing_nullable=False)
    op.alter_column('realtime_data', 'data',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtime_data', 'data',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=False)
    op.alter_column('project_daily_report', 'report_content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_comment='日报内容(JSON格式)',
               existing_nullable=False)
    op.alter_column('project', 'settlement_period',
               existing_type=mysql.VARCHAR(length=20),
               comment='业绩核算期，格式YYYY-MM',
               existing_comment='业绩核算期（手工填写，常见YYYYMM如202608，兼容YYYY-MM）',
               existing_nullable=True)
    op.alter_column('history_data', 'data',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=False)
    op.alter_column('collection_data', 'data',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=False)
    op.create_table('_tz_migration_sentinel',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migrated_at', mysql.DATETIME(), nullable=False),
    sa.Column('note', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
