"""add age column to user1

Revision ID: 3522a752b39e
Revises: eb185cccf38a
Create Date: 2026-08-06 16:42:58.702550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3522a752b39e'
down_revision: Union[str, None] = 'eb185cccf38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_contact', sa.String(length=50), nullable=True, comment='对接人'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_contact')
    # ### end Alembic commands ###
