"""用户增加公司字段变更

Revision ID: 389e011724d6
Revises: 3522a752b39e
Create Date: 2026-08-07 09:56:42.857153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389e011724d6'
down_revision: Union[str, None] = '3522a752b39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.String(length=128), nullable=True, comment='公司'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
