"""添加部门表/公司表

Revision ID: 4c40a9474980
Revises: 81faa4a5d172
Create Date: 2026-08-13 15:18:58.404699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c40a9474980'
down_revision: Union[str, None] = '81faa4a5d172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_ibfk_2'), 'companies', type_='foreignkey')
    op.drop_constraint(op.f('companies_ibfk_1'), 'companies', type_='foreignkey')
    op.drop_constraint(op.f('departments_ibfk_2'), 'departments', type_='foreignkey')
    op.drop_constraint(op.f('departments_ibfk_3'), 'departments', type_='foreignkey')
    op.add_column('users', sa.Column('company_id', sa.String(length=64), nullable=True, comment='公司ID'))
    op.add_column('users', sa.Column('department_id', sa.String(length=64), nullable=True, comment='部门ID'))
    op.alter_column('users', 'company',
               existing_type=mysql.VARCHAR(length=128),
               comment='公司名称（废弃，改用 company_id）',
               existing_comment='公司',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=128),
               comment='部门/团队名称（废弃，改用 department_id）',
               existing_comment='部门/团队',
               existing_nullable=True)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=128),
               comment='部门/团队',
               existing_comment='部门/团队名称（废弃，改用 department_id）',
               existing_nullable=True)
    op.alter_column('users', 'company',
               existing_type=mysql.VARCHAR(length=128),
               comment='公司',
               existing_comment='公司名称（废弃，改用 company_id）',
               existing_nullable=True)
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'company_id')
    op.create_foreign_key(op.f('departments_ibfk_3'), 'departments', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(op.f('departments_ibfk_2'), 'departments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('companies_ibfk_1'), 'companies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('companies_ibfk_2'), 'companies', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###
