"""查看时常

Revision ID: 65386a53a7fd
Revises: d3223179214c
Create Date: 2026-08-14 18:38:10.081091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65386a53a7fd'
down_revision: Union[str, None] = 'd3223179214c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_operation_logs', sa.Column('ended_at', sa.DateTime(), nullable=True, comment='查看结束时间（仅 VIEW 有值）'))
    op.add_column('task_operation_logs', sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='查看时长（秒，仅 VIEW 有值）'))
    op.add_column('tasks', sa.Column('attachment_analysis', sa.JSON(), nullable=True, comment='附件分析记忆：{object_path: {filename, kind, summary, analyzed_at}}，供 AI 判断每次需重新分析的附件，避免重复分析'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachment_analysis')
    op.drop_column('task_operation_logs', 'duration_seconds')
    op.drop_column('task_operation_logs', 'ended_at')
    # ### end Alembic commands ###
