"""后台新增字段, 操作记录

Revision ID: 66896f9ef955
Revises: fe798370169d
Create Date: 2026-08-11 16:28:04.648646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66896f9ef955'
down_revision: Union[str, None] = 'fe798370169d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_openid', sa.String(length=128), nullable=True, comment='绑定的微信open_id（讨论区消息转发到微信用）'))
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=False)
    op.drop_column('users', '{')
    op.drop_column('users', 'PK\x03\x04')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('PK\x03\x04', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('users', sa.Column('{', mysql.VARCHAR(length=256), nullable=True))
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_column('users', 'wechat_openid')
    # ### end Alembic commands ###
