"""user增加上级字段

Revision ID: 81faa4a5d172
Revises: 66896f9ef955
Create Date: 2026-08-12 19:59:53.709949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81faa4a5d172'
down_revision: Union[str, None] = '66896f9ef955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supervisor_id', sa.String(length=64), nullable=True, comment='直属上级用户ID（全局行政汇报线）'))
    op.create_index(op.f('ix_users_supervisor_id'), 'users', ['supervisor_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_supervisor_id'), table_name='users')
    op.drop_column('users', 'supervisor_id')
    # ### end Alembic commands ###
