"""expand_license_code_column

Revision ID: 85291bac5d4c
Revises: 26021ebb27b1
Create Date: 2026-07-29 13:07:06.603256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85291bac5d4c'
down_revision: Union[str, None] = '26021ebb27b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_license', sa.Column('machine_code', sa.String(length=200), nullable=True, comment='机器码/MAC地址'))
    op.alter_column('project_license', 'license_code',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='授权码',
               existing_nullable=False)
    op.alter_column('users', 'avatar_resource_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='头像资源ID',
               existing_nullable=True)
    op.alter_column('users', 'responsibility_modules',
               existing_type=mysql.JSON(),
               comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_comment='责任模块',
               existing_nullable=True)
    op.alter_column('users', 'job_level',
               existing_type=mysql.TINYINT(),
               comment='职级，数值越高越不优先接单（1=一线, 2=管理/审核, 3=仅兜底...），默认1',
               existing_comment='职级默认1',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'duty_text',
               existing_type=mysql.TEXT(),
               comment='职责画像文本，供 AI 派单匹配参考',
               existing_comment='职责画像文本',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'duty_text',
               existing_type=mysql.TEXT(),
               comment='职责画像文本',
               existing_comment='职责画像文本，供 AI 派单匹配参考',
               existing_nullable=True)
    op.alter_column('users', 'job_level',
               existing_type=mysql.TINYINT(),
               comment='职级默认1',
               existing_comment='职级，数值越高越不优先接单（1=一线, 2=管理/审核, 3=仅兜底...），默认1',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'responsibility_modules',
               existing_type=mysql.JSON(),
               comment='责任模块',
               existing_comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_nullable=True)
    op.alter_column('users', 'avatar_resource_id',
               existing_type=mysql.INTEGER(),
               comment='头像资源ID',
               existing_nullable=True)
    op.alter_column('project_license', 'license_code',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_comment='授权码',
               existing_nullable=False)
    op.drop_column('project_license', 'machine_code')
    # ### end Alembic commands ###
