"""记录项目对接人

Revision ID: d3223179214c
Revises: 4c40a9474980
Create Date: 2026-08-14 10:54:59.186734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3223179214c'
down_revision: Union[str, None] = '4c40a9474980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'contact_person_id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               comment='对接人ID（与 users.id 同长度）',
               existing_comment='对接人ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'contact_person_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               comment='对接人ID',
               existing_comment='对接人ID（与 users.id 同长度）',
               existing_nullable=True)
    # ### end Alembic commands ###
