"""后台新增字段

Revision ID: e90261182a2f
Revises: f2f1bc37b495
Create Date: 2026-07-31 16:29:29.311861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90261182a2f'
down_revision: Union[str, None] = 'f2f1bc37b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_license', sa.Column('max_vehicles', sa.Integer(), nullable=True, comment='允许最大车数，为空表示不限制'))
    op.add_column('roles', sa.Column('role_type', sa.String(length=20), server_default='project', nullable=False, comment='角色类型：system=系统角色，project=项目角色'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'role_type')
    op.drop_column('project_license', 'max_vehicles')
    # ### end Alembic commands ###
