"""check diff

Revision ID: f43e2566ff01
Revises: fd1a8809adad
Create Date: 2026-08-27 19:49:17.659449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f43e2566ff01'
down_revision: Union[str, None] = 'fd1a8809adad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'profile_text',
               existing_type=mysql.TEXT(),
               comment='部门职责描述（AI 派单部门分类用）',
               existing_nullable=True)
    op.alter_column('departments', 'examples',
               existing_type=mysql.JSON(),
               comment='典型工单示例（[{title, dept}]）',
               existing_nullable=True)
    # 先创建新索引，再删除旧索引：task_id 上存在外键约束（FK -> tasks.id），
    # MySQL 不允许删除外键所依赖的唯一索引（错误 1553）。
    # 必须先建好 ix_task_comment_read_record_task_id 作为后备索引，再删 ix_crr_task_id。
    op.create_index(op.f('ix_task_comment_read_record_comment_id'), 'task_comment_read_record', ['comment_id'], unique=False)
    op.create_index(op.f('ix_task_comment_read_record_id'), 'task_comment_read_record', ['id'], unique=False)
    op.create_index(op.f('ix_task_comment_read_record_task_id'), 'task_comment_read_record', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_comment_read_record_username'), 'task_comment_read_record', ['username'], unique=False)
    op.drop_index(op.f('ix_crr_task_id'), table_name='task_comment_read_record')
    op.drop_index(op.f('ix_crr_username'), table_name='task_comment_read_record')
    op.drop_table_comment(
        'task_comment_read_record',
        existing_comment='单条评论的已读记录（飞书式已读名单）',
        schema=None
    )
    op.alter_column('tasks', 'assigned_to',
               existing_type=mysql.VARCHAR(length=50),
               comment='处理者ID（users.id）',
               existing_comment='处理者ID',
               existing_nullable=True)
    op.alter_column('users', 'responsibility_modules',
               existing_type=mysql.JSON(),
               comment='责任模块 三层结构 {产品: {界面: [功能]}}',
               existing_comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=20),
               comment='用户手机号（企业微信通知 @ 人用）',
               existing_nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='用户手机号（企业微信通知 @ 人用）',
               existing_nullable=True)
    op.alter_column('users', 'responsibility_modules',
               existing_type=mysql.JSON(),
               comment='责任模块 ["车端","任务调度","地图编辑"...]',
               existing_comment='责任模块 三层结构 {产品: {界面: [功能]}}',
               existing_nullable=True)
    op.alter_column('tasks', 'assigned_to',
               existing_type=mysql.VARCHAR(length=50),
               comment='处理者ID',
               existing_comment='处理者ID（users.id）',
               existing_nullable=True)
    op.create_table_comment(
        'task_comment_read_record',
        '单条评论的已读记录（飞书式已读名单）',
        existing_comment=None,
        schema=None
    )
    # 回滚同样要先建旧索引（含 ix_crr_task_id）作为外键后备，再删新索引。
    op.create_index(op.f('ix_crr_username'), 'task_comment_read_record', ['username'], unique=False)
    op.create_index(op.f('ix_crr_task_id'), 'task_comment_read_record', ['task_id'], unique=False)
    op.drop_index(op.f('ix_task_comment_read_record_username'), table_name='task_comment_read_record')
    op.drop_index(op.f('ix_task_comment_read_record_task_id'), table_name='task_comment_read_record')
    op.drop_index(op.f('ix_task_comment_read_record_id'), table_name='task_comment_read_record')
    op.drop_index(op.f('ix_task_comment_read_record_comment_id'), table_name='task_comment_read_record')
    op.alter_column('departments', 'examples',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='典型工单示例（[{title, dept}]）',
               existing_nullable=True)
    op.alter_column('departments', 'profile_text',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='部门职责描述（AI 派单部门分类用）',
               existing_nullable=True)
    # ### end Alembic commands ###
