"""新增字段settlement_period

Revision ID: f5b92f785846
Revises: 85291bac5d4c
Create Date: 2026-07-31 10:18:45.903987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b92f785846'
down_revision: Union[str, None] = '85291bac5d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('settlement_period', sa.String(length=20), nullable=True, comment='业绩核算期，格式YYYY-MM'))
    op.create_index('idx_project_settlement_period', 'project', ['settlement_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_settlement_period', table_name='project')
    op.drop_column('project', 'settlement_period')
    # ### end Alembic commands ###
