"""OpenAI-compatible LLM client with mock mode for testing."""

import json
from typing import Any, AsyncGenerator, Dict, List, Optional

from automation.logger import get_logger


_MOCK_RESPONSES: Dict[str, str] = {
    "error": "Based on the error code E1001, this indicates a sensor communication fault. "
             "Recommended actions:\n1. Check sensor cable connection\n"
             "2. Reboot the robot controller\n3. Run diagnostic test",
    "reset": "To reset your robot:\n1. Press and hold the power button for 10 seconds\n"
             "2. Wait for all LEDs to turn off\n3. Wait 30 seconds\n"
             "4. Press power button to restart",
    "default": "This is a mock LLM response for testing purposes. "
               "The actual response will be generated by the configured LLM model.",
}


class LLMClient:
    """OpenAI-compatible LLM client.

    Supports real API calls (via openai.AsyncOpenAI) and mock mode for testing.

    Usage:
        llm = LLMClient(mock=True)
        response = await llm.chat([{"role": "user", "content": "Hello"}])

        llm = LLMClient(api_key="sk-xxx", base_url="https://api.deepseek.com")
        response = await llm.chat(messages)
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: str = "deepseek-chat",
        mock: bool = False,
    ):
        self.mock = mock
        self.model = model
        self._log = get_logger("ai.llm")

        if not mock:
            self._check_openai()
            from openai import AsyncOpenAI
            self._client = AsyncOpenAI(
                api_key=api_key or "",
                base_url=base_url or "https://api.deepseek.com",
            )
        else:
            self._client = None

    @staticmethod
    def _check_openai() -> None:
        try:
            import openai  # noqa: F401
        except ImportError:
            raise ImportError(
                "openai package is required. Install: pip install openai"
            )

    async def chat(
        self,
        messages: List[Dict[str, str]],
        **kwargs: Any,
    ) -> str:
        """Send a chat request and return the response text."""
        if self.mock:
            return self._mock_chat(messages)

        self._log.debug("Chat request: %s messages, model=%s", len(messages), self.model)
        resp = await self._client.chat.completions.create(
            model=self.model,
            messages=messages,
            **kwargs,
        )
        text = resp.choices[0].message.content or ""
        self._log.debug("Chat response: %d chars", len(text))
        return text

    async def chat_stream(
        self,
        messages: List[Dict[str, str]],
        **kwargs: Any,
    ) -> AsyncGenerator[str, None]:
        """Stream a chat response, yielding text chunks."""
        if self.mock:
            yield self._mock_chat(messages)
            return

        stream = await self._client.chat.completions.create(
            model=self.model,
            messages=messages,
            stream=True,
            **kwargs,
        )
        async for chunk in stream:
            delta = chunk.choices[0].delta if chunk.choices else None
            if delta and delta.content:
                yield delta.content

    def _mock_chat(self, messages: List[Dict[str, str]]) -> str:
        """Return a mock response based on the last user message content."""
        last = messages[-1]["content"].lower() if messages else ""
        for keyword, response in _MOCK_RESPONSES.items():
            if keyword in last:
                return response
        return _MOCK_RESPONSES["default"]
